/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apu.oodj.vaccinestation;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import apu.oodj.vaccinestation.Internals.FileHandling;
import apu.oodj.vaccinestation.Internals.Managerial.VaccineRequest;
import apu.oodj.vaccinestation.Internals.Users.Administrator;
import apu.oodj.vaccinestation.Internals.Vaccine.Vaccine;

/**
 *
 * @author N4O
 */
public class AdminAddRemoveVaccine extends javax.swing.JFrame {
    private Administrator admin;
    private ArrayList<Vaccine> vaccines;

    /**
     * Creates new form AdminAddRemoveVaccine
     */
    public AdminAddRemoveVaccine(Administrator admin) {
        initComponents();
        this.admin = admin;

        String[] rawVaccines;
        try {
            rawVaccines = FileHandling.ReadFile("vaccines");
        } catch (FileNotFoundException ex) {
            rawVaccines = new String[] {};
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to read vaccines information, please contact Admin!");
            new HomepageAdmin(this.admin).setVisible(true);
            this.setVisible(false);
            return;
        }

        this.vaccines = new ArrayList<Vaccine>();
        for (String rawVaccine : rawVaccines) {
            vaccines.add(Vaccine.ParseData(rawVaccine));
        }

        this.refreshVaccineList();
    }

    public void refreshVaccineList() {
        DefaultListModel<Vaccine> model = new DefaultListModel<>();
        for (Vaccine vaccine : vaccines) {
            model.addElement(vaccine);
        }
        lstVaccine.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstVaccine = new javax.swing.JList<>();
        btnModifyVaccine = new javax.swing.JButton();
        btnRemoveVaccine = new javax.swing.JButton();
        btnCreateNew = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Add/Remove Vaccine");

        lstVaccine.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstVaccine.setToolTipText("");
        jScrollPane1.setViewportView(lstVaccine);

        btnModifyVaccine.setText("Modify");
        btnModifyVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyVaccineActionPerformed(evt);
            }
        });

        btnRemoveVaccine.setText("Remove");
        btnRemoveVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveVaccineActionPerformed(evt);
            }
        });

        btnCreateNew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreateNew.setText("Create New");
        btnCreateNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewActionPerformed(evt);
            }
        });

        btnGoBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGoBack.setText("Go Back");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGoBack)
                    .addComponent(btnCreateNew)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRemoveVaccine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModifyVaccine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModifyVaccine)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemoveVaccine)))
                .addGap(18, 18, 18)
                .addComponent(btnCreateNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnGoBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyVaccineActionPerformed
        Vaccine sel = lstVaccine.getSelectedValue();
        if (sel == null) {
            JOptionPane.showMessageDialog(this, "Please select a vaccine to modify!");
            return;
        }

        new AdminModifyVaccine(this.admin, sel).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnModifyVaccineActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        new HomepageAdmin(this.admin).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnRemoveVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveVaccineActionPerformed
        Vaccine sel = lstVaccine.getSelectedValue();
        if (sel == null) {
            JOptionPane.showMessageDialog(this, "Please select a vaccine to remove!");
            return;
        }
        int selIndex = lstVaccine.getSelectedIndex();
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove: " + sel.getName() + "?");
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // Remove from database
        try {
            FileHandling.RemoveById("vaccines", sel.getId());
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Unable to remove vaccine because an error occured!");
            return;
        }

        // Remove from list
        this.vaccines.remove(selIndex);
        JOptionPane.showMessageDialog(this, "Vaccine removed!");
        this.refreshVaccineList();

        // Remove the vaccine type from request.
        String[] vaccinesRequest;
        try {
            vaccinesRequest = FileHandling.ReadFile("vaccinerequest");
        } catch (FileNotFoundException ex) {
            vaccinesRequest = new String[] {};
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Unable to remove vaccine from requests because an error occured!");
            return;
        }

        ArrayList<String> newRequests = new ArrayList<>();
        for (String xd : vaccinesRequest) {
            VaccineRequest parse = VaccineRequest.ParseData(xd);
            if (parse.getVaccine().getId().equals(sel.getId())) {
                // Vac found, skip
                continue;
            }
            newRequests.add(xd);
        }

        try {
            FileHandling.WriteString("vaccinerequest", newRequests, false);
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Unable to save vaccine requests because an error occured!");
        }
    }//GEN-LAST:event_btnRemoveVaccineActionPerformed

    private void btnCreateNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewActionPerformed
        new AdminAddNewVaccine(this.admin).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCreateNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddRemoveVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddRemoveVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddRemoveVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddRemoveVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddRemoveVaccine(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateNew;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnModifyVaccine;
    private javax.swing.JButton btnRemoveVaccine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Vaccine> lstVaccine;
    // End of variables declaration//GEN-END:variables
}
