/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apu.oodj.vaccinestation;

import java.awt.Color;
import javax.swing.JOptionPane;

import apu.oodj.vaccinestation.Internals.Users.Administrator;

/**
 *
 * @author asus
 */
public class AdminAddRemoveVaccineName extends javax.swing.JFrame {
    private Administrator admin;

    /**
     * Creates new form AdminAddRemoveVaccineName
     */
    public AdminAddRemoveVaccineName(Administrator admin) {
        initComponents();
        this.admin = admin;
        txtRemoveVaccine.setEnabled(false);
        txtRemoveVaccine.setText("This Box is Highly Secured !! So If You Really Want to Delete Vaccine, Click The 'BUTTON' Above");
        txtRemoveVaccine.setBackground(Color.black);
        txtNewVaccineName.setEnabled(false);
        txtNewVaccineName.setText("This Box is Highly Secured !! Click 'BUTTON' Above To Activate This TextBox");
        txtNewVaccineName.setBackground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAvailableVaccine = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        btnClickRemoveVaccine = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNewVaccineName = new javax.swing.JTextField();
        btnAddNewVaccine = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnClickNewVaccineName = new javax.swing.JButton();
        txtRemoveVaccine = new javax.swing.JTextField();
        btnMove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("ADD NEW VACCINE / REMOVE OLD VACCINE ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("AVAILABLE VACCINE NAME");

        lstAvailableVaccine.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstAvailableVaccine);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("REMOVE VACCINE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnClickRemoveVaccine.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClickRemoveVaccine.setText("CLICK HERE");
        btnClickRemoveVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickRemoveVaccineActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ADD NEW VACCINE ??");

        btnAddNewVaccine.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddNewVaccine.setText("OK");
        btnAddNewVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewVaccineActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("REMOVE SELECTED VACCINE??");

        btnClickNewVaccineName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClickNewVaccineName.setText("CLICK HERE");
        btnClickNewVaccineName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickNewVaccineNameActionPerformed(evt);
            }
        });

        txtRemoveVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRemoveVaccineActionPerformed(evt);
            }
        });
        txtRemoveVaccine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRemoveVaccineKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRemoveVaccineKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRemoveVaccineKeyTyped(evt);
            }
        });

        btnMove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMove.setForeground(new java.awt.Color(0, 153, 0));
        btnMove.setText("BACK");
        btnMove.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRemoveVaccine)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(187, 187, 187))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(btnClickRemoveVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnClickNewVaccineName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(btnMove, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNewVaccineName, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddNewVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClickRemoveVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRemoveVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClickNewVaccineName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewVaccineName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNewVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnMove, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClickRemoveVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickRemoveVaccineActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"PLEASE DELETE ALL THE WORDS IN THE BOX AND TYPE \n\n            I AGREE REMOVE THIS VACCINE");
        txtRemoveVaccine.setEnabled(true); 
        txtRemoveVaccine.setBackground(Color.white);
        txtRemoveVaccine.setText("%$%!^&*((*&^%%))&^%!!@#$^^#!!!!@#$#@$%^$%@!***&**&^%$$$@#!!@#$*&!#$$%^!@#$^%$@!");
    }//GEN-LAST:event_btnClickRemoveVaccineActionPerformed

    private void txtRemoveVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRemoveVaccineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRemoveVaccineActionPerformed

    private void btnClickNewVaccineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickNewVaccineNameActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"PLEASE TYPE NEW VACCINE ON THE BOX");
        txtNewVaccineName.setEnabled(true);
        txtNewVaccineName.setBackground(Color.white);
        txtNewVaccineName.setText("");
    }//GEN-LAST:event_btnClickNewVaccineNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                    //DELETE VACCINE NAME ( NOT YET DONE )
        String removeVaccine = txtRemoveVaccine.getText();
        String availableVaccine = lstAvailableVaccine.getSelectedValue();
        if(removeVaccine.equals("I AGREE REMOVE THIS VACCINE")){
        JOptionPane.showMessageDialog(this, "SUCCESSFULLY DELETE THIS VACCINE");
        JOptionPane.showMessageDialog(this, "VACCINE NAME : " + availableVaccine);
        txtRemoveVaccine.setEnabled(false);
        txtRemoveVaccine.setBackground(Color.black);
        txtRemoveVaccine.setText("This Box is Highly Secured !! So If You Really Want to Delete Vaccine, Click The 'BUTTON' Above");
        }else if(removeVaccine.equals("This Box is Highly Secured !! So If You Really Want to Delete Vaccine, Click The 'BUTTON' Above")){
            JOptionPane.showMessageDialog(this, "YOU NOT YET PRESS THE BUTTON ABOVE TO DELETING THE VACCINE");
        }else if(!removeVaccine.equals("I AGREE REMOVE THIS VACCINE")){
            JOptionPane.showMessageDialog(this, "       WRONG TEXT INPUT !! \n\nDELETING VACCINE POSTPONED");
            txtRemoveVaccine.setEnabled(false);
            txtRemoveVaccine.setText("This Box is Highly Secured !! So If You Really Want to Delete Vaccine, Click The 'BUTTON' Above");        
            txtRemoveVaccine.setBackground(Color.black);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddNewVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewVaccineActionPerformed
        // TODO add your handling code here:
        String addVaccine = txtNewVaccineName.getText();
        if(addVaccine.equals("This Box is Highly Secured !! Click 'BUTTON' Above To Activate This TextBox")){
            JOptionPane.showMessageDialog(this, "YOU NOT YET PRESS THE BUTTON ABOVE TO ADD NEW VACCINE");
        }else if(addVaccine.isEmpty()){
            JOptionPane.showMessageDialog(this, "   EMPTY BOX DETECTED\nFAILED ADD NEW VACCINE");
            txtNewVaccineName.setEnabled(false);
            txtNewVaccineName.setBackground(Color.black);
            txtNewVaccineName.setText("This Box is Highly Secured !! Click 'BUTTON' Above To Activate This TextBox");
        }
        else{
            JOptionPane.showMessageDialog(this, "SUCCESSFULLY ADD NEW VACCINE");
            JOptionPane.showMessageDialog(this, "VACCINE NAME : " + addVaccine);
            txtNewVaccineName.setEnabled(false);
            txtNewVaccineName.setBackground(Color.black);
            txtNewVaccineName.setText("This Box is Highly Secured !! Click 'BUTTON' Above To Activate This TextBox");
        }
        
    }//GEN-LAST:event_btnAddNewVaccineActionPerformed

    private void txtRemoveVaccineKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRemoveVaccineKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRemoveVaccineKeyPressed

    private void txtRemoveVaccineKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRemoveVaccineKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRemoveVaccineKeyTyped

    private void txtRemoveVaccineKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRemoveVaccineKeyReleased
        //CHANGED INPUT FROM TEXTBOX INTO UPPERCASE
        String removeText = txtRemoveVaccine.getText();
        txtRemoveVaccine.setText(removeText.toUpperCase());
    }//GEN-LAST:event_txtRemoveVaccineKeyReleased

    private void btnMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveActionPerformed
        // TODO add your handling code here:
        new AdminVaccineSlots(this.admin).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddRemoveVaccineName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddRemoveVaccineName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddRemoveVaccineName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddRemoveVaccineName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddRemoveVaccineName(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewVaccine;
    private javax.swing.JButton btnClickNewVaccineName;
    private javax.swing.JButton btnClickRemoveVaccine;
    private javax.swing.JButton btnMove;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstAvailableVaccine;
    private javax.swing.JTextField txtNewVaccineName;
    private javax.swing.JTextField txtRemoveVaccine;
    // End of variables declaration//GEN-END:variables
}
