name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ["11", "14", "16"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
          architecture: x64
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Test with Maven
        run: mvn test
